name: Build Tweak
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl git software-properties-common

    - name: Clone Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos
        echo "THEOS=$GITHUB_WORKSPACE/theos" >> $GITHUB_ENV

    - name: Compile Tweak
      run: |
        export THEOS=$GITHUB_WORKSPACE/theos
        make package
